layout_spectrum: 0.5797777
typography_spectrum: 0.1917562
color:
  saturation: 0.9024457
  brandStrength: 0.7363613
  lightness: 0.5023894
  rhythmicContrast: 0.5310633
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: 'Maximiliano Paradiso '
