collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.1917562
color:
  saturation: 0.7891278
  brandStrength: 0.7363613
  lightness: 0.4402629
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 0.7473118
layout_spectrum: 0.8870967
name: 'Maximiliano Paradiso '
